### ISSUE TITLE
Weather Plugin #idea

### ISSUE THREAD

**Issue by erinjo** [idno/idno#156]
This is primarily a reminder note for myself.

It would be nice to have a weather plugin.  It could fetch your location from the browser, but you could also manually enter your zip code.  Fields would let you edit or enter city / state / country details as desired.  Option to select Celsius or Fahrenheit.  Space also to leave your own little note.  Plugin would query a weather database to record the current forecast for that location.  I don't know if people would want to push that info to social networks, but I suppose the option could always be included.  Including a private/public status for this update would also be handy.

**Comment by benwerd** [comment]
Closing this out of the issues list - but if there's still interest in a weather plugin, maybe we should take it to the mailing list!
