### ISSUE TITLE
Preselect Social Network Options #enhancement

### ISSUE THREAD

**Issue by erinjo** [idno/idno#157]
A lot of times I wouldn't normally suggest preselecting the send to network web actions, but in this case - with things like status update and checkin - it might make sense to preselect all available networks and let users uncheck as desired.  

Or, even better, maybe users could specify their preferred networks in the settings, ex. for status update also check Twitter, FB is an option but it stays unchecked.

Looking at Buffer, it seems my Twitter is always preselected (even though I send to App.net more often).

**Comment by benwerd** [comment]
I'm closing this for now - we can revisit later if required.
