### ISSUE TITLE
Support MySQL / MariaDB back-end

### ISSUE THREAD

**Issue by benwerd** [idno/idno#207]
Because most people can't support MongoDB.

HOWEVER, I want to avoid doing this in the way that Elgg did it. Need something significantly faster.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/207" class="u-in-reply-to"></a>I imagine this could be closed...?

**Comment by physcocode** [comment]
+1'ed close it!

**Comment by benwerd** [comment]
Yeah, I suppose this might work by now ;)

Thanks guys :)
