### ISSUE TITLE
Plugins for Instagram, Pinterest & LinkedIn

### ISSUE THREAD

**Issue by TheDavidJohnson** [idno/idno#461]
I'm playing with both the hosted solution and the open source project to examine the possibilities available to me (and to my clients) as a marketer. It's especially valuable to create content on sites we control and then syndicate to social networks. Twitter and Facebook are working beautifully. It would be valuable to us to have the ability to push content to:
* Instagram,
* Pinterest, and
* LinkedIn

Thanks for the awesome work!

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/461" class="u-in-reply-to"></a>As an FYI, Linkedin plugin is now used in production, and Instagram + Pinterest don't have open APIs, so I suspect this ticket can be closed...

**Comment by benwerd** [comment]
Indeed. Closing this out. Instagram, Pinterest, others may follow as backfeed plugins in the future.
