### ISSUE TITLE
Invalid "Set site private" property

### ISSUE THREAD

**Issue by Phyks** [idno/idno#647]
Hi,

On my Known instance, to make it public, I had to set "Set site private" to "Yes". I think the value of "Yes" and "No" in the template may be inverted with the db ones. My template is tabula rasa.

Thanks

**Comment by mapkyca** [comment]
Confirmed, this is the wrong way round. Feel free to send a PR :)

**Comment by Phyks** [comment]
@mapkyca done, thanks :)
