### ISSUE TITLE
Feed not ordered by date on user profile

### ISSUE THREAD

**Issue by Phyks** [idno/idno#663]
Hi,

I'm running a single-user instance of Known. On the homepage, I display entries and they are all sorted by date, which is what I was expecting and is coherent with the "Older" and "Newer" links at the bottom of the page.

However, on my profile page, they seems to no longer be sorted in any way which is unexpected and seems to be an issue as the links at the bottom of the page still read "Older" and "Newer".

This can be seen [here](https://known.phyks.me/) and [here](https://known.phyks.me/profile/phyks).

Thanks

**Comment by benwerd** [comment]
Sorry to hear you're having problems with this - out of interest, are you using MySQL or MongoDB as your back-end database?

**Comment by mapkyca** [comment]
It may be unrelated but I'm seeing this as a result of my Flickr Importer - homepage is as expected, but profile appears out of order. I'm wondering if it's a mixup between sorting on created ts vs updated ts (for the importer, created is aaaages ago, but updated is just now since the object has just been imported)

**Comment by Phyks** [comment]
@benwerd I am using the MySQL backend as it was almost straightforward and (I think) the most widely used setup among users.

@mapkyca +1 for this lead. Most of my articles were in fact imported from my previous blog, using the API and sending a payload with title, body and created (so I'm basically in the same situation with imported ages ago). Thus, no updated was sent and it should be set to "now" according to your comment.

However, I'm not sure whether they are sorted in the imported order either...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/663" class="u-in-reply-to"></a>Ok, I've replicated this on the homepage as well... what looks like is happening is that the ActivityStreamPost wrapper for a given object is not inheriting created from the wrapped object... this causes objects to display the correct published time, but appear out of order in searches. PR to come...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/663" class="u-in-reply-to"></a>To fix existing data after patch, there needs to be some sql/script-fu to set the ActivityStreamPost object's created time to the same as it's contained object.

**Comment by mapkyca** [comment]
You need to loop through all the ActivityStreamPost objects and rebind them with their container objects so that created is the same in both.

Something like the following pseudocode:

For each ActivityStreamPost as $post {

$post->created = $post->getObject()->created;
$post->save();

}

**Comment by Phyks** [comment]
Thanks !
