### ISSUE TITLE
Blog broken after uploading new files

### ISSUE THREAD

**Issue by davidmead** [idno/idno#668]
I downloaded the latest .zip and replaced everything that was less than 5 days old on my server.

When going to my install (http://blog.davidjohnmead.com) the site is now down. I get this error:

>Warning: require_once(/nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/Symfony/Component/ClassLoader/UniversalClassLoader.php): failed to open stream: No such file or directory in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/Idno/start.php on line 39

and

>Fatal error: require_once(): Failed opening required '/nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/external/Symfony/Component/ClassLoader/UniversalClassLoader.php' (include_path='.:/usr/local/php-5.5.18/share/pear') in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/Idno/start.php on line 39

When I open start.php, on line 39 it is looking for
````
/external/Symfony/Component/ClassLoader/UniversalClassLoader.php
````
but that ClassLoader folder is empty on my server, and in the .zip I downloaded.

Do I need to go to https://github.com/symfony/ClassLoader, grab the contents and upload to my server?

Any suggestions?

**Comment by benwerd** [comment]
It sounds like you grabbed the zip from GitHub, which doesn't work (although we may fix this shortly). GitHub doesn't support git submodules, which we use extensively.

You should either grab the code from withknown.com, or perform a full git export, if you have the ability on your machine.

**Comment by davidmead** [comment]
OK, Thanks. I've been pulling the .zip down in the past and haven't had issues. Is this a recent change to submodules?

I just sent you an email, so you can ignore that :-)

I'll try the full git export.

**Comment by davidmead** [comment]
I cloned IDNO and plugins to my desktop so I have the latest, including the submodules. Blog is up & running again but I am now getting the following error on http://blog.davidjohnmead.com/admin/plugins/

>Warning: file_exists(): open_basedir restriction in effect. File(/nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/IdnoPlugins/StaticPages.zip/plugin.ini) is not within the allowed path(s): (/nfs:/tmp:/usr/local:/etc/apache2/gs-bin) in /nfs/c03/h06/mnt/56448/domains/blog.davidjohnmead.com/html/Idno/Core/Plugins.php on line 103

Any ideas?

**Comment by benwerd** [comment]
Your host appears to have restricted filesystem access to applications outside of your web path, making it very hard to check if plugins are available. You should probably file this with them, and hopefully they can get the setting changed.

As a side note, your StaticPages folder name shouldn't have a .zip at the end :)

**Comment by davidmead** [comment]
Oh. I didn't notice that was zipped up. I unzipped it and replaced the .zip with the folder and seems to have fixed it. It's a zipped file in GitHub FYI https://github.com/idno/idno/blob/master/IdnoPlugins/StaticPages.zip.

Thanks for the help.

**Comment by benwerd** [comment]
Whoops - that was an internal file that wasn't intended to be committed.
Thanks!

On Fri, Jan 2, 2015 at 12:17 PM, David Mead <notifications@github.com>
wrote:

> Oh. I didn't notice that was zipped up. I unzipped it and replaced the
> .zip with the folder and seems to have fixed it. It's a zipped file in
> GitHub FYI
> https://github.com/idno/idno/blob/master/IdnoPlugins/StaticPages.zip.
>
> Thanks for the help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/idno/issues/668#issuecomment-68558462>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373
