### ISSUE TITLE
Site privacy setting opposite

### ISSUE THREAD

**Issue by davidmead** [idno/idno#676]
At some point something has changed in the code.

My settings have been always been 'no' to Set site private on the site config page. Seems I have to set it to yes for my sites content to show up without logging in now:

![skitch](https://cloud.githubusercontent.com/assets/1266930/5616992/b0760b8a-94d7-11e4-8119-cbd99700bcc0.png)

>@davidmead Is the link in your reply a webmention? BTW, I couldn't see it--had to login
https://twitter.com/robknight/status/552153788195160064

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/676" class="u-in-reply-to"></a>Actually, no (see #647)... basically the setting was reversed, so when you set "no" you were actually setting "yes".

**Comment by davidmead** [comment]
Um. That doesn't make sense. Is this going to be fixed? Couldn't tell from #647

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/676" class="u-in-reply-to"></a>It is fixed. That's why the setting has reversed...

To clarify, before the fix the *value* of the setting was the opposite of the *display*... so a No, was in fact a Yes.

**Comment by davidmead** [comment]
Oh, OK. I'll go and grab the updated files and push them to my site.  Last update I did was last week.

**Comment by benwerd** [comment]
Yeah, sorry. We fixed this recently.
