### ISSUE TITLE
feature request : share to ello.co

### ISSUE THREAD

**Issue by jpcaruana** [idno/idno#678]
Hi,

ello.co is a new social network: it would be great to be able to share content on ello vith known, as we can already do with facebook and twitter

https://ello.co

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/678" class="u-in-reply-to"></a>That would be cool, sadly ello currently don't have an API Known can talk to, and it doesn't appear to be on their todo list either.

Hopefully in the future...

**Comment by jpcaruana** [comment]
ok thanks for your input.
I see there are some unofficial APIs: here https://gist.github.com/conatus/cc665f917d5558c123bc and there http://www.programmableweb.com/api/unofficial-ello maybe we could use that as an inspiration (and I read https://indiewebcamp.com/Ello which is verry clear about 'ello api state of the art')

**Comment by mapkyca** [comment]
Interesting.... might be possible to do a post then...

**Comment by benwerd** [comment]
Ello's API and features really aren't state of the art. As a company, we
can't use unofficial APIs, and I recommend that you don't either, because
doing so could violate local laws (although I'm not a lawyer and this isn't
legal advice).

They've talked about charging for API access and I hope they don't do this.

**Comment by physcocode** [comment]
+1 for @benwerd  , totally agreed !

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/678" class="u-in-reply-to"></a>Obvs. anything using this unofficial api would be a community plugin.

It's a crazy world if programmatically replicating what a browser does anyway is illegal, but then we live in a world where downloading public domain academic articles and making them available can get you hounded to suicide by your government... soo...

Personally I'm not terribly interested in ello as a concept... Not to dump on someone elses project, but it's currently just another silo, which addresses none of the problems (surveillance, single point of failure) with the other silos out there.

**Comment by physcocode** [comment]
@mapkyca  too diplomatic

**Comment by benwerd** [comment]
I'm going to close this for now as it's not something that we can support officially. Once Ello announces their public API and terms, we can revisit it. @jpcaruana, thanks so much for filing this! Sorry we couldn't help for now.

**Comment by jpcaruana** [comment]
thanks
