### ISSUE TITLE
No default check in `/account/settings/notifications/`

### ISSUE THREAD

**Issue by Phyks** [idno/idno#693]
Hi,

It seems there is no default value for the radio buttons on `/account/settings/notifications/`. Actually, I never went to this page before and found that no radio buttons were checked.

I checked "Whenever someone interacts with my content" and, then, it remained checked, even after a page refresh.

**Comment by benwerd** [comment]
Great catch. Thank you.

**Comment by Phyks** [comment]
Thanks for closing this this quick! :)

**Comment by benwerd** [comment]
We like notifications!
