### ISSUE TITLE
audio posts should use the proposed "u-audio" property (not u-media)

### ISSUE THREAD

**Issue by tantek** [idno/idno#694]
Per http://microformats.org/wiki/h-entry#Proposed_Additions audio posts should use the proposed "u-audio" property (not u-media) cc: @aaronpk @dissolve.

E.g. http://werd.io/content/streamingmedia/
http://werd.io/2014/shoplifters-and-thieves-podcastsunday
Etc.

**Comment by benwerd** [comment]
Thanks again for the PR!
