### ISSUE TITLE
"Connect Services" iframe inception

### ISSUE THREAD

**Issue by kylewm** [idno/idno#700]
When I visit the page http://kylewm.withknown.com/account/settings/services it seems be loading itself in an iframe (which loads itself in an iframe (which loads itself in an iframe))

![known-bug](https://cloud.githubusercontent.com/assets/950127/5687289/157e152e-9800-11e4-84a8-27189c558ac3.png)

**Comment by benwerd** [comment]
Argh. Thanks for reporting this! It's a recurring problem with hubs that I'm working on right now.

**Comment by benwerd** [comment]
Hopefully this is fixed!

**Comment by benwerd** [comment]
@kylewm Can you confirm that this is working for you now?

**Comment by kylewm** [comment]
Looks good! :+1:
