### ISSUE TITLE
Password reset link sent with wrong URL protocol (http instead of https)

### ISSUE THREAD

**Issue by michielbdejong** [idno/idno#712]
With Known 0.6.5, the link in the password reset email is displayed with http instead of with https.

I had a look through the code -

Like some [other templates](https://github.com/idno/idno/issues/608), the email template uses \Idno\Core\site()->config()->getURL(), which [eventually](https://github.com/idno/idno/blob/master/Idno/Core/Config.php#L156) ends up [asking Apache](https://github.com/idno/idno/blob/master/Idno/Common/Page.php#L675), instead of looking at getDisplayURL, which is what the user supplied in ["This is your site's URL."](https://github.com/idno/idno/blob/master/templates/default/admin/home.tpl.php#L49).

What is the difference between getURL and getDisplayURL?

**Comment by benwerd** [comment]
getDisplayURL() more elegantly flips URI scheme based on how you're accessing the site. We're switching to it across the board.

**Comment by michielbdejong** [comment]
Cool! I'll wait for that, then.
