### ISSUE TITLE
Problem with tagged content

### ISSUE THREAD

**Issue by davidmead** [idno/idno#716]
I wanted to post a URL that showed all photos on my blog that were tagged #365daysofme. So I thought I could use `http://blog.davidjohnmead.com/content/photos/#365daysofme` but that didn't work.

If I click on a tag in a post I would get `?q=%23` added in the URL. So if I then changed the URL to `http://blog.davidjohnmead.com/content/photos/?q=%23365daysofme` it works.

Is there a way we can implement something similar to Twitter where entering `https://twitter.com/#cleama` redirects to `https://twitter.com/hashtag/cleama` making it a little more user-friendly?

**Comment by benwerd** [comment]
Interesting! We haven't done this because of the standard anchor behavior (and I had no idea Twitter did this redirect!). Users might want to put a TOC into a blog post, for example. It's definitely a neat idea though ... I wonder if blog.davidjohnmead.com/tag/365daysofme would be acceptable?

**Comment by davidmead** [comment]
Well `blog.davidjohnmead.com/tag/365daysofme` would work for me :-) 

I think as long as there's a way to display everything with a certain tag it would be a start. The nice thing about Known is that content is available as `/photos` or `/checkins` so a mechanism to filter items further would enhance internal linking and syndication.

Also, WordPress has `http://davidjohnmead.com/tag/android/` implemented.

**Comment by benwerd** [comment]
Yeah, the /tag/* URL pattern is well-used. We'll do it! :)

**Comment by davidmead** [comment]
Great :-)

**Comment by benwerd** [comment]
Re-opening until we push the code!
