### ISSUE TITLE
Upload files through the API?

### ISSUE THREAD

**Issue by Phyks** [idno/idno#721]
Hi,

Is there any built-in mechanism to post data + files in Known?

I mean, right now, I use the Known API to post content to my instance. This way, I can use my own text editor, and this works flawlessly! But, I do not have any ways to upload files as well.

For instance, if I want to post a long post and add images in it, using the web editor, I just have to add them via the toolbar and the upload is done and the image is linked. If I use the API, however, my current solution is to `scp` the images manually, which is not very handy.

So, is there such a mechanism builtin? And what do you think of implementing it (as a part of Known API or an extension of Micropub for instance)?

Thanks!

**Comment by mapkyca** [comment]
Yes, the api supports files (where the endpoint does) via post. You can do this from curl directly, or code. Take a look at my known to known cross poster plugin as an example of this being done...

**Comment by Phyks** [comment]
Sorry for the delay, I was really busy lately. Your plugin will give me all the necessary infos I need I think, as it is exactly that I want to be able to do! (but from a Python script and not a different Known instance).

Thanks!
